name: SkillTree
version: '1.0-SNAPSHOT'
main: ru.traiwy.skilltree.SkillTree
api-version: '1.20'
commands:
  skilltree:
    usage: /skilltree
    description: Opens the skill tree menu
    permissions: skilltree.admin
